### ISSUE TITLE
Unable to get Buzz to operate RTX 5090 with build 1.3.0 on Windows 11

### ISSUE THREAD

**Issue by AgardnerAU** [chidiwilliams/buzz#1134]
Attempting to transcribe any files fails. Cuda 12.8 is installed + latest drivers. 
 NVIDIA-SMI 572.83                 Driver Version: 572.83         CUDA Version: 12.8 

With the following unhandled exception:

`Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "buzz\transcriber\whisper_file_transcriber.py", line 105, in transcribe_whisper
  File "buzz\transcriber\whisper_file_transcriber.py", line 208, in transcribe_openai_whisper
  File "whisper\__init__.py", line 155, in load_model
  File "torch\nn\modules\module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Whisper:
	While copying the parameter named "encoder.blocks.0.attn.query.weight", whose dimensions in the model are torch.Size([1280, 1280]) and whose dimensions in the checkpoint are torch.Size([1280, 1280]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.0.attn.key.weight", whose dimensions in the model are torch.Size([1280, 1280]) and whose dimensions in the checkpoint are torch.Size([1280, 1280]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "buzz\buzz.py", line 38, in main
  File "PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 48, in _freeze_support
  File "multiprocessing\spawn.py", line 122, in spawn_main
  File "multiprocessing\spawn.py", line 135, in _main
  File "multiprocessing\process.py", line 329, in _bootstrap
AttributeError: 'NoneType' object has no attribute 'write'`

The error logs also show:
[2025-03-26 21:30:01,198] settings.__init__:14 DEBUG -> Settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
[2025-03-26 21:30:01,203] model_loader.<module>:42 DEBUG -> Model root directory: C:\Users\ag\AppData\Local\Buzz\Buzz\Cache\models
[2025-03-26 21:30:01,242] utils._find_ffmpeg_extension:114 DEBUG -> Loading FFmpeg6
[2025-03-26 21:30:01,242] utils._find_ffmpeg_extension:120 DEBUG -> Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
  File "torio\_extension\utils.py", line 105, in _find_versionsed_ffmpeg_extension
  File "<frozen importlib.util>", line 95, in find_spec
ModuleNotFoundError: No module named 'torio.lib'
[2025-03-26 21:30:01,243] utils._find_ffmpeg_extension:114 DEBUG -> Loading FFmpeg5
[2025-03-26 21:30:01,243] utils._find_ffmpeg_extension:120 DEBUG -> Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File "torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
  File "torio\_extension\utils.py", line 105, in _find_versionsed_ffmpeg_extension
  File "<frozen importlib.util>", line 95, in find_spec
ModuleNotFoundError: No module named 'torio.lib'
[2025-03-26 21:30:01,243] utils._find_ffmpeg_extension:114 DEBUG -> Loading FFmpeg4
[2025-03-26 21:30:01,243] utils._find_ffmpeg_extension:120 DEBUG -> Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File "torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
  File "torio\_extension\utils.py", line 105, in _find_versionsed_ffmpeg_extension
  File "<frozen importlib.util>", line 95, in find_spec
ModuleNotFoundError: No module named 'torio.lib'
[2025-03-26 21:30:01,243] utils._find_ffmpeg_extension:114 DEBUG -> Loading FFmpeg
[2025-03-26 21:30:01,243] utils._find_ffmpeg_extension:120 DEBUG -> Failed to load FFmpeg extension.
Traceback (most recent call last):
  File "torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
  File "torio\_extension\utils.py", line 105, in _find_versionsed_ffmpeg_extension
  File "<frozen importlib.util>", line 95, in find_spec
ModuleNotFoundError: No module named 'torio.lib'
[2025-03-26 21:30:02,355] settings.__init__:14 DEBUG -> Settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
[2025-03-26 21:30:02,362] settings.__init__:14 DEBUG -> Settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
[2025-03-26 21:30:02,363] settings.__init__:14 DEBUG -> Settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
[2025-03-26 21:30:02,363] buzz.main:61 DEBUG -> app_dir: C:\Users\ag\AppData\Local\Programs\Buzz\_internal
[2025-03-26 21:30:02,363] buzz.main:62 DEBUG -> log_dir: C:\Users\ag\AppData\Local\Buzz\Buzz\Logs
[2025-03-26 21:30:02,363] buzz.main:63 DEBUG -> cache_dir: C:\Users\ag\AppData\Local\Buzz\Buzz\Cache
[2025-03-26 21:30:02,363] buzz.main:64 DEBUG -> data_dir: C:\Users\ag\AppData\Local\Buzz\Buzz
[2025-03-26 21:30:02,376] settings.__init__:14 DEBUG -> Settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
[2025-03-26 21:30:02,387] db._setup_db:39 DEBUG -> Database connection opened: C:\Users\ag\AppData\Local\Buzz\Buzz\Buzz.sqlite
[2025-03-26 21:30:02,393] settings.__init__:14 DEBUG -> Settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
[2025-03-26 21:30:02,415] settings.__init__:14 DEBUG -> Settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
[2025-03-26 21:30:02,498] file_transcriber_queue_worker.run:43 DEBUG -> Waiting for next transcription task
[2025-03-26 21:30:13,336] backend._load_plugins:243 DEBUG -> Loading KWallet
[2025-03-26 21:30:13,336] backend._load_plugins:243 DEBUG -> Loading SecretService
[2025-03-26 21:30:13,336] backend._load_plugins:243 DEBUG -> Loading Windows
[2025-03-26 21:30:13,339] __init__.<module>:11 DEBUG -> Loaded cffi backend
[2025-03-26 21:30:13,415] backend._load_plugins:243 DEBUG -> Loading chainer
[2025-03-26 21:30:13,416] backend._load_plugins:243 DEBUG -> Loading libsecret
[2025-03-26 21:30:13,416] backend._load_plugins:243 DEBUG -> Loading macOS
[2025-03-26 21:30:13,420] settings.__init__:14 DEBUG -> Settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
[2025-03-26 21:30:13,421] settings.__init__:14 DEBUG -> Settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
[2025-03-26 21:30:19,359] file_transcriber_queue_worker.run:81 DEBUG -> Starting next transcription task
[2025-03-26 21:30:19,367] whisper_file_transcriber.transcribe:52 DEBUG -> Starting whisper file transcription, task = FileTranscriptionTask(transcription_options=TranscriptionOptions(language=None, task=<Task.TRANSCRIBE: 'transcribe'>, model=TranscriptionModel(), word_level_timings=False, extract_speech=False, temperature=(0.0, 0.2, 0.4, 0.6, 0.8, 1.0), initial_prompt='', openai_access_token='', enable_llm_translation=False, llm_prompt='', llm_model=''), file_transcription_options=FileTranscriptionOptions(file_paths=['C:/Users/ag/Downloads/Music/sample audio files for speech recognition.wav'], url=None, output_formats=set()), model_path='C:\\Users\\ag\\AppData\\Local\\Buzz\\Buzz\\Cache\\models\\whisper\\tiny.pt', id=89883085, uid=UUID('67501611-b285-48d0-9d3a-a1c1a335ac7a'), segments=[], status=None, error=None, queued_at=None, started_at=None, completed_at=None, output_directory=None, source=<Source.FILE_IMPORT: 'file_import'>, file_path='C:/Users/ag/Downloads/Music/sample audio files for speech recognition.wav', url=None, fraction_downloaded=0.0)
[2025-03-26 21:30:19,367] whisper_file_transcriber.transcribe:57 DEBUG -> CUDA version detected: 12.1
[2025-03-26 21:30:23,853] whisper_file_transcriber.transcribe:78 DEBUG -> whisper process completed with code = 1, time taken = 0:00:04.485469, number of segments = 0
[2025-03-26 21:30:23,853] file_transcriber.run:90 ERROR -> 
Traceback (most recent call last):
  File "buzz\transcriber\file_transcriber.py", line 88, in run
  File "buzz\transcriber\whisper_file_transcriber.py", line 87, in transcribe
Exception: Unknown error
[2025-03-26 21:30:23,854] file_transcriber_queue_worker.run:43 DEBUG -> Waiting for next transcription task

**Comment by AgardnerAU** [comment]
[traceback error.txt](https://github.com/user-attachments/files/19476059/traceback.error.txt)

[logs.txt](https://github.com/user-attachments/files/19476065/logs.txt)

**Comment by raivisdejus** [comment]
@AgardnerAU In the installation exe we bundle cuda 12.1. My current hypothesis is that this version is too old to know about RTX 5090.

You could test a few torch versions to see if any of them work on RTX 5090.

General notes are here https://github.com/chidiwilliams/buzz/blob/main/CONTRIBUTING.md#windows

The commands below will install latest stable torch with CUDA 12.6

```
python -m venv venv
.\venv\Scripts\activate
git clone --recursive https://github.com/chidiwilliams/buzz.git
cd buzz
poetry env activate
poetry install
cp -r .\dll_backup\ .\buzz\
pip3 uninstall torch torchaudio
pip3 install torch torchaudio --index-url https://download.pytorch.org/whl/cu126
python -m buzz
```

For me it took quite long to load, like a minute or two. Faster whisper was failing, but regular Whisper
 and Huggingface whisper worked. Search in the list for "openai" and select the model size you want.


Test two - the torch with CUDA 12.8

```
pip3 uninstall torch torchaudio
pip3 install --pre torch torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128 
```

If you run into any issues while testing, feel free to post them here, will try to help sort them out.

**Comment by AgardnerAU** [comment]
Thanks. No matter what I try, I can't get poetry install to complete.
Is there a way that I can use the buzz.exe installer and then just upgrade the pytorch instance within that environment?

`
Installing the current project: buzz-captions (1.3.0)Preparing build environment with build-system requirements poetry-core>=2.0.0, ctypesgen, setuptools, cmake, polib
process_begin: CreateProcess(NULL, uname -s, ...) failed.
Makefile:15: pipe: No error
process_begin: CreateProcess(NULL, uname -m, ...) failed.
Makefile:16: pipe: No error
process_begin: CreateProcess(NULL, uname -m, ...) failed.
Makefile:94: pipe: No error
process_begin: CreateProcess(NULL, uname -m, ...) failed.
Makefile:106: pipe: No error
process_begin: CreateProcess(NULL, mktemp, ...) failed.
Makefile:218: pipe: Bad file descriptor
forfiles /p buzz\locale /c "cmd /c python ..\..\msgfmt.py -o @path\LC_MESSAGES\buzz.mo @path\LC_MESSAGES\buzz.po"

for dir in buzz/locale/*/ ; do \
        python msgfmt.py -o $dir/LC_MESSAGES/buzz.mo $dir/LC_MESSAGES/buzz.po; \
done
dir was unexpected at this time.
make: [Makefile:235: translation_mo] Error 255 (ignored)
cd buzz && ctypesgen ../whisper.cpp/whisper.h -lwhisper -o whisper_cpp.py
INFO: Status: Preprocessing C:\Users\ag\AppData\Local\Temp\tmpifrnj4_5.h
INFO: Status: gcc -E -U __GNUC__ -dD "-D__extension__=" "-D__const=const" "-D__asm__(x)=" "-D__asm(x)=" "-DCTYPESGEN=1" "C:\Users\ag\AppData\Local\Temp\tmpifrnj4_5.h"
ERROR: gcc -E: In file included from C:/msys64/mingw64/include/_mingw.h:306,
ERROR: gcc -E:                  from C:/msys64/mingw64/include/corecrt.h:10,
ERROR: gcc -E:                  from C:/msys64/mingw64/include/crtdefs.h:10,
ERROR: gcc -E:                  from C:/msys64/mingw64/include/stddef.h:7,
ERROR: gcc -E:                  from C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/include/stddef.h:1,
ERROR: gcc -E:                  from L:\buzz\whisper.cpp\ggml.h:218,
ERROR: gcc -E:                  from L:\buzz\whisper.cpp\whisper.h:4,
ERROR: gcc -E:                  from C:\Users\ag\AppData\Local\Temp\tmpifrnj4_5.h:1:
ERROR: gcc -E: C:/msys64/mingw64/include/vadefs.h:35:2: error: #error VARARGS not implemented for this compiler
ERROR: gcc -E:    35 | #error VARARGS not implemented for this compiler
ERROR: gcc -E:       |  ^~~~~
INFO: Status: Parsing C:\Users\ag\AppData\Local\Temp\tmpifrnj4_5.h
ERROR: C:/msys64/mingw64/include/corecrt.h:75: Syntax error at 'uintptr_t'
ERROR: C:/msys64/mingw64/include/stddef.h:26: Syntax error at '__threadhandle'
ERROR: C:/msys64/mingw64/include/corecrt_stdio_config.h:16: Syntax error at '*'
ERROR: C:/msys64/mingw64/include/corecrt_stdio_config.h:16: Syntax error at ';'
ERROR: C:/msys64/mingw64/include/corecrt_stdio_config.h:17: Syntax error at ';'
ERROR: C:/msys64/mingw64/include/stdio.h:161: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:167: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:173: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:178: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:187: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:193: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:199: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:205: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:213: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:221: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:229: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:238: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:246: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:255: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:263: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:681: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:695: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:919: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:923: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:927: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:934: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:936: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:940: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:944: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:950: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:956: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:962: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:973: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:976: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:982: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:988: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:1222: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:1224: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:1225: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:1236: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/stdio.h:1239: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:523: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:532: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:533: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:535: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:537: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:539: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:548: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:549: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:550: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:552: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:555: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:556: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:559: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:560: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:563: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:564: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:567: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:568: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:570: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:572: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:574: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:576: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:579: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:580: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:832: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:833: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:835: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:839: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:845: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:847: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:849: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:851: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:876: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:877: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:879: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:881: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:884: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:885: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:888: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:889: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:892: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:893: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:896: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:898: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:900: Syntax error at 'va_list'
ERROR: C:/msys64/mingw64/include/sec_api/stdio_s.h:901: Syntax error at 'va_list'
ERROR: <built-in>:0: Syntax error at '\n'
ERROR: <built-in>:0: Syntax error at '\n'
ERROR: <built-in>:0: Syntax error at '\n'
ERROR: <built-in>:0: Syntax error at '\n'
ERROR: <built-in>:0: Syntax error at '\n'
ERROR: <built-in>:0: Syntax error at '\n'
ERROR: <built-in>:0: Syntax error at '\n'
ERROR: <built-in>:0: Syntax error at '\n'
ERROR: C:/msys64/mingw64/include/_mingw_mac.h:324: Syntax error at '\n'
INFO: Status: Processing description list.
INFO: Status: Writing to whisper_cpp.py.
INFO: Status: Wrapping complete.
Installing the current project: buzz-captions (1.3.0)`

**Comment by AgardnerAU** [comment]
Alas, I seem to be getting further away from the goal :-0

I had uninstalled Buzz, and then re-installed to but it won't load at all now. 

Apologies for my newbie lack of knowledge in trying to progress. I've followed the steps here:
https://github.com/chidiwilliams/buzz/blob/main/CONTRIBUTING.md#windows
and spent a few hours with various LLM's trying to self-service the issues, but have been unable to progress. 

![Image](https://github.com/user-attachments/assets/56d56b1e-5c3d-4762-b474-864cc46c0402)

**Comment by raivisdejus** [comment]
> Alas, I seem to be getting further away from the goal :-0
> 
> I had uninstalled Buzz, and then re-installed to but it won't load at all now.
> 
> Apologies for my newbie lack of knowledge in trying to progress. I've followed the steps here: https://github.com/chidiwilliams/buzz/blob/main/CONTRIBUTING.md#windows and spent a few hours with various LLM's trying to self-service the issues, but have been unable to progress.

@AgardnerAU This issue is caused by the transcript database from the new version having extra columns that are not present in the released version. To solve this issue you need to delete the `Buzz.sqlite` file in `%USERPROFILE%\AppData\Local\Buzz\Buzz\` folder. 

The errors you see in the previous post can be ignored. IMO it will still work. Just try to run the buzz with `python -m buzz`. I get the same errors and it works. Not sure what exactly causes these. Let's try to ignore them. 

When you run Buzz, you can also ignore errors for FFmpeg. Buzz tries to load FFmpeg by several different means and depending on the system some of them will throw the errors, but FFmpeg eventually should get loaded.

**Comment by AgardnerAU** [comment]
@raivisdejus - Thanks. Removing that sqlite file allows the Windows install to now run with the initial errors. 

I am pretty confident the latest nightly pytorch build will work as it's resolved some comfyui issues.

Is there a way that I can run these commands "within" the Buzz windows .exe installation environment? I.e. install via the standard .exe build, then update pytorch files. 

I am struggling to get the Poetry environment to build via the manual install, so if I can just do spot surgery that may work. 

pip3 uninstall torch torchaudio
pip3 install torch torchaudio --index-url https://download.pytorch.org/whl/cu128

**Comment by raivisdejus** [comment]
Check the installation directory in Program Files, all files get collected in a subfolder. You can change them there. And it may work.

**Comment by raivisdejus** [comment]
This is how we install GPU support during the builds https://github.com/chidiwilliams/buzz/blob/main/.github/workflows/ci.yml#L139-L145

You may be able to adjust the commands to match the versions you need. For the very latest versions of `nvidia` libraries you can remove the version requirement. That will install the latest versions. 

Also the windows local build instructions have been updated https://github.com/chidiwilliams/buzz/blob/main/CONTRIBUTING.md#windows

And also the very latest version did update some dependencies that were targeting older library versions so was causing issues. In short if this has not been resolved yet, try again on the very latest version of the code

**Comment by raivisdejus** [comment]
I assume issue was resolved. Feel free to re-open if more help is needed. Commits from the weekend also updated some library versions, so could give this another if still relevant.
