### ISSUE TITLE
ERROR/ Failed to execute script 'main' due to unhandled exception: 'NoneType' object has no attribute 'write'

### ISSUE THREAD

**Issue by hpnzss** [chidiwilliams/buzz#1180]
Buzz was working normally on my previous PC. Recently, I upgraded my PC from a 3700X with a 1066S GPU to a 9700X with a 5070 Ti. Since the upgrade, Buzz no longer works. Below is the error information:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "buzz\transcriber\whisper_file_transcriber.py", line 105, in transcribe_whisper
  File "buzz\transcriber\whisper_file_transcriber.py", line 204, in transcribe_openai_whisper
  File "whisper\__init__.py", line 155, in load_model
  File "torch\nn\modules\module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Whisper:
	While copying the parameter named "encoder.blocks.0.attn.query.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.0.attn.key.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.0.attn.value.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.0.attn.out.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.0.mlp.0.weight", whose dimensions in the model are torch.Size([2048, 512]) and whose dimensions in the checkpoint are torch.Size([2048, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.0.mlp.2.weight", whose dimensions in the model are torch.Size([512, 2048]) and whose dimensions in the checkpoint are torch.Size([512, 2048]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.1.attn.query.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.1.attn.key.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.1.attn.value.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.1.attn.out.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.1.mlp.0.weight", whose dimensions in the model are torch.Size([2048, 512]) and whose dimensions in the checkpoint are torch.Size([2048, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.1.mlp.2.weight", whose dimensions in the model are torch.Size([512, 2048]) and whose dimensions in the checkpoint are torch.Size([512, 2048]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.2.attn.query.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.2.attn.key.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.2.attn.value.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.2.attn.out.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.2.mlp.0.weight", whose dimensions in the model are torch.Size([2048, 512]) and whose dimensions in the checkpoint are torch.Size([2048, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.2.mlp.2.weight", whose dimensions in the model are torch.Size([512, 2048]) and whose dimensions in the checkpoint are torch.Size([512, 2048]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.3.attn.query.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.3.attn.key.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.3.attn.value.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.3.attn.out.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.3.mlp.0.weight", whose dimensions in the model are torch.Size([2048, 512]) and whose dimensions in the checkpoint are torch.Size([2048, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.3.mlp.2.weight", whose dimensions in the model are torch.Size([512, 2048]) and whose dimensions in the checkpoint are torch.Size([512, 2048]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.4.attn.query.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.4.attn.key.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.4.attn.value.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.4.attn.out.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.4.mlp.0.weight", whose dimensions in the model are torch.Size([2048, 512]) and whose dimensions in the checkpoint are torch.Size([2048, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.4.mlp.2.weight", whose dimensions in the model are torch.Size([512, 2048]) and whose dimensions in the checkpoint are torch.Size([512, 2048]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.5.attn.query.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.5.attn.key.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.5.attn.value.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.5.attn.out.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.5.mlp.0.weight", whose dimensions in the model are torch.Size([2048, 512]) and whose dimensions in the checkpoint are torch.Size([2048, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "encoder.blocks.5.mlp.2.weight", whose dimensions in the model are torch.Size([512, 2048]) and whose dimensions in the checkpoint are torch.Size([512, 2048]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.0.attn.query.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.0.attn.key.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.0.attn.value.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.0.attn.out.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.0.cross_attn.query.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.0.cross_attn.key.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.0.cross_attn.value.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.0.cross_attn.out.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.0.mlp.0.weight", whose dimensions in the model are torch.Size([2048, 512]) and whose dimensions in the checkpoint are torch.Size([2048, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.0.mlp.2.weight", whose dimensions in the model are torch.Size([512, 2048]) and whose dimensions in the checkpoint are torch.Size([512, 2048]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.1.attn.query.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.1.attn.key.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.1.attn.value.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.1.attn.out.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.1.cross_attn.query.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.1.cross_attn.key.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.1.cross_attn.value.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.1.cross_attn.out.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.1.mlp.0.weight", whose dimensions in the model are torch.Size([2048, 512]) and whose dimensions in the checkpoint are torch.Size([2048, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.1.mlp.2.weight", whose dimensions in the model are torch.Size([512, 2048]) and whose dimensions in the checkpoint are torch.Size([512, 2048]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.2.attn.query.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.2.attn.key.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.2.attn.value.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.2.attn.out.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.2.cross_attn.query.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.2.cross_attn.key.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.2.cross_attn.value.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.2.cross_attn.out.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.2.mlp.0.weight", whose dimensions in the model are torch.Size([2048, 512]) and whose dimensions in the checkpoint are torch.Size([2048, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.2.mlp.2.weight", whose dimensions in the model are torch.Size([512, 2048]) and whose dimensions in the checkpoint are torch.Size([512, 2048]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.3.attn.query.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.3.attn.key.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.3.attn.value.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.3.attn.out.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.3.cross_attn.query.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.3.cross_attn.key.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.3.cross_attn.value.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.3.cross_attn.out.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.3.mlp.0.weight", whose dimensions in the model are torch.Size([2048, 512]) and whose dimensions in the checkpoint are torch.Size([2048, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.3.mlp.2.weight", whose dimensions in the model are torch.Size([512, 2048]) and whose dimensions in the checkpoint are torch.Size([512, 2048]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.4.attn.query.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.4.attn.key.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.4.attn.value.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.4.attn.out.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.4.cross_attn.query.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.4.cross_attn.key.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.4.cross_attn.value.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.4.cross_attn.out.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.4.mlp.0.weight", whose dimensions in the model are torch.Size([2048, 512]) and whose dimensions in the checkpoint are torch.Size([2048, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.4.mlp.2.weight", whose dimensions in the model are torch.Size([512, 2048]) and whose dimensions in the checkpoint are torch.Size([512, 2048]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.5.attn.query.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.5.attn.key.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.5.attn.value.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.5.attn.out.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.5.cross_attn.query.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.5.cross_attn.key.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.5.cross_attn.value.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.5.cross_attn.out.weight", whose dimensions in the model are torch.Size([512, 512]) and whose dimensions in the checkpoint are torch.Size([512, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.5.mlp.0.weight", whose dimensions in the model are torch.Size([2048, 512]) and whose dimensions in the checkpoint are torch.Size([2048, 512]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
	While copying the parameter named "decoder.blocks.5.mlp.2.weight", whose dimensions in the model are torch.Size([512, 2048]) and whose dimensions in the checkpoint are torch.Size([512, 2048]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "buzz\buzz.py", line 38, in main
  File "PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 50, in _freeze_support
  File "multiprocessing\spawn.py", line 122, in spawn_main
  File "multiprocessing\spawn.py", line 135, in _main
  File "multiprocessing\process.py", line 329, in _bootstrap
AttributeError: 'NoneType' object has no attribute 'write'

**Comment by raivisdejus** [comment]
@hpnzss Can you try the latest development version https://chidiwilliams.github.io/buzz/docs/faq#9-where-can-i-get-latest-development-version

We have had some reports on 50XX series cards and my guess is that library versions in the released version are too old and do not support the newer cards. Latest development version has some of the used libraries updated, but we may need to update them to the very latest versions. 

Next release is around the corner, need to polish some last kinks.

**Comment by hpnzss** [comment]
@raivisdejus Thank you very much for your reply. I installed the latest development version from the link you provided, but unfortunately, the error remains the same.

**Comment by raivisdejus** [comment]
@hpnzss Easiest workaround is to use Huggingface or Faster whisper types. If any of them work on your hardware, speeds should be very similar. For Huggingface type search "openai" in the model field and select the size you want.

**Comment by hpnzss** [comment]
@raivisdejus Thanks so much. Hugging Face still doesn’t work — same error. But Faster Whisper works for me.

**Comment by BumbleTree** [comment]
Same Issue with 5070Ti including when trying the HuggingFace Whisper Models

**Comment by ilvsx** [comment]
same

**Comment by raivisdejus** [comment]
@ilvsx @BumbleTree @hpnzss One thing we can try is to:
- Follow general instructions here https://github.com/chidiwilliams/buzz/blob/main/CONTRIBUTING.md
- Update CUDA dependencies
```
pip3 install -U transformers
pip3 install -U torch==2.7.1+cu128 torchaudio==2.7.1+cu128 --index-url https://download.pytorch.org/whl/cu128
pip3 install nvidia-cublas-cu12==12.8.3.14 nvidia-cuda-cupti-cu12==12.8.57 nvidia-cuda-nvrtc-cu12==12.8.61 nvidia-cuda-runtime-cu12==12.8.57 nvidia-cudnn-cu12==9.7.1.26 nvidia-cufft-cu12==11.3.3.41 nvidia-curand-cu12==10.3.9.55 nvidia-cusolver-cu12==11.7.2.55 nvidia-cusparse-cu12==12.5.4.2 nvidia-cusparselt-cu12==0.6.3 nvidia-nvjitlink-cu12==12.8.61 nvidia-nvtx-cu12==12.8.55 --index-url https://pypi.ngc.nvidia.com
```
- Run buzz with `python -m buzz`

With updated libraries Huggingface whisper large v3 from openai repo worked for me on my RTX 3090.

If it still does not work we will need to wait for library updated.


On windows you can try the latest development version with Vulkan GPU support for whisper.cpp from here https://github.com/chidiwilliams/buzz/actions/runs/15857122551

Speed wise on GPU all whisper versions are of comparable speed. For custom models whisper.cpp supports the ctranslate2 versions.

**Comment by raivisdejus** [comment]
Closing this as duplicate of https://github.com/chidiwilliams/buzz/issues/1229
